// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADqCA5FEh_9icdvQhfU8ksSqB6oBP6WTM',
    appId: '1:935552577:web:8146f31833401e2bcf88c0',
    messagingSenderId: '935552577',
    projectId: 'flutter-phones-shop',
    authDomain: 'flutter-phones-shop.firebaseapp.com',
    storageBucket: 'flutter-phones-shop.firebasestorage.app',
    measurementId: 'G-2ME3H6JGRR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYfadUs_ModGrc1rOfbeydL9GMYesek-E',
    appId: '1:935552577:android:3d4cae6df792a812cf88c0',
    messagingSenderId: '935552577',
    projectId: 'flutter-phones-shop',
    storageBucket: 'flutter-phones-shop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4fw65bYrfEnXU5dTcJv1b5x2VAjaAh_w',
    appId: '1:935552577:ios:afb6ad872c511c00cf88c0',
    messagingSenderId: '935552577',
    projectId: 'flutter-phones-shop',
    storageBucket: 'flutter-phones-shop.firebasestorage.app',
    iosBundleId: 'com.example.flutterPhonesShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4fw65bYrfEnXU5dTcJv1b5x2VAjaAh_w',
    appId: '1:935552577:ios:afb6ad872c511c00cf88c0',
    messagingSenderId: '935552577',
    projectId: 'flutter-phones-shop',
    storageBucket: 'flutter-phones-shop.firebasestorage.app',
    iosBundleId: 'com.example.flutterPhonesShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADqCA5FEh_9icdvQhfU8ksSqB6oBP6WTM',
    appId: '1:935552577:web:c875e6afab5c8cdfcf88c0',
    messagingSenderId: '935552577',
    projectId: 'flutter-phones-shop',
    authDomain: 'flutter-phones-shop.firebaseapp.com',
    storageBucket: 'flutter-phones-shop.firebasestorage.app',
    measurementId: 'G-05KNZFKR2T',
  );
}
